### ISSUE TITLE
Braced section globs broken?

### ISSUE THREAD

**Issue by thebuilder** [floatdrop/gulp-watch#187] opened 2015-07-21 07:49 UTC
Tried updating to the latest 4.3.x release, and globs i use with braced sections now fail to trigger.

```js
//Watch globs
config.jade.watch = "**/*.{json,html,jade}";
config.style.watch = "**/{*.less,*.css,*.styl}";

//Watch implementation example:
var watch = require('gulp-watch');
watch(config.style.watch, function(file) {
	execute();
});
```

It's possible other types of special selectors are failing, but these are the ones i'm using.

Reverting back to 4.2.5 and everything is working.

**Comment by floatdrop** [comment] 2015-07-22 09:21
I'm on `4.3.3` and it is working (afaik):

```
❯ node index.js
<File "src/scss/sub/index.css" <Buffer 61 73 64 61 73 0a 61 73 64 61 73 64 0a>>
<File "src/scss/sub/index.css" <Buffer 61 73 64 61 73 0a 61 73 64 61 73 64 61 73 64 61 0a>>
^C

~/github.com/test-watch 7s
❯ cat index.js
var watch = require('gulp-watch');

watch('**/{*.less,*.css,*.styl}', function(file) {
    console.log(file);
});
```

**Comment by thebuilder** [comment] 2015-07-22 09:41
Weird. Just tested it a bit more. It now seems to work on my machine, but not on my colleague's. Updated to 4.3.3, and compared the *node_modules*. Only difference is that my machine is using chokidar 1.0.4, and the other machine 1.0.5.

**Comment by facupedrazzini** [comment] 2015-08-01 03:56
Having this problem when update to 4.3.x, rollback to 4.2.x and work fine:

    /xxx/node_modules/gulp-watch/node_modules/glob/node_modules/minimatch/minimatch.js:108
        throw new TypeError('glob pattern string required')
              ^
    TypeError: glob pattern string required

This is my gulp watch task:

    gulp.task('watch', function () {
        gulp.watch(['app/**/*.js', 'app/**/*.html'], ['default']);
        watch(config.path.dist).pipe(connect.reload());
    });

**Comment by Spown** [comment] 2015-08-18 23:56
I also get 

 > /xxx/node_modules/gulp-watch/node_modules/glob/node_modules/minimatch/minimatch.js:108
 >    throw new TypeError('glob pattern string required')
 >          ^
 > TypeError: glob pattern string required

when I delete an non empty folder while watching xxx/**/*.*

**Comment by m3fawner** [comment] 2015-09-09 12:20
@facupedrazzini I have confirmed that a rollback from 4.3.x to 4.2.5 fixed the problem for me, as well. Has anybody been able to solve this in a cleaner fashion?

**Comment by jmlv** [comment] 2015-10-02 05:48
Same error when delete an non empty folder

**Comment by timschambers** [comment] 2015-10-12 20:47
I ran into a similar issue, and then, following the advice here in this thread, rolled-back to 4.2.5 which fixed the problem. 

This code:
<code>
require("gulp-watch")(["template_prototyper/bc/Breadcrumb/src/"], function( vinyl ) {
                        return templateBuild();
                    });
</code>

Threw this error when I edited any file in "template_prototyper/bc/Breadcrumb/src/":

<code>
somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/glob/node_modules/minimatch/minimatch.js:108
    throw new TypeError('glob pattern string required')
          ^
TypeError: glob pattern string required
    at new Minimatch (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/glob/node_modules/minimatch/minimatch.js:108:11)
    at setopts (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/glob/common.js:112:20)
    at new Glob (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/glob/glob.js:117:3)
    at EventEmitter.processEvent (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/index.js:92:35)
    at EventEmitter.emit (events.js:110:17)
    at EventEmitter.<anonymous> (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/chokidar/index.js:137:38)
    at EventEmitter.FSWatcher._emit (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/chokidar/index.js:152:5)
    at EventEmitter.<anonymous> (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/chokidar/lib/fsevents-handler.js:172:14)
    at addOrChange (somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/chokidar/lib/fsevents-handler.js:177:7)
    at somepathname/5.1/internal_utilities/apex_node_build/node_modules/gulp-watch/node_modules/chokidar/lib/fsevents-handler.js:183:35

</code>

@floatdrop  any idea why this might be happening?

**Comment by Bertuzb** [comment] 2015-10-24 15:34
i can confirm this issue, for the time i rollbacked to 4.2.5

**Comment by UltCombo** [comment] 2016-06-19 03:37
Looks like a dupe of #192, this issue has been fixed upstream.

Let us know if you still manage to reproduce the problem.

**Closed by UltCombo** 2016-06-19 03:37 UTC
