### ISSUE TITLE
Watch doesn't see new files when files path begins with './'

### ISSUE THREAD

**Issue by kasperekt** [floatdrop/gulp-watch#122] opened 2015-01-15 20:42 UTC
With that code (notice: `./`):

````javascript
watch('./frontend/templates/**/*.jade', gulpTemplates);
````

plugin seemed to not see new files, but I found some solution on main `gulp` repo, that when I write the path without `./` it works fine. Like this:

````javascript
watch('frontend/templates/**/*.jade', gulpTemplates);
````

**Comment by floatdrop** [comment] 2015-01-16 05:52
Duplicate of https://github.com/floatdrop/gulp-watch/issues/111

**Closed by floatdrop** 2015-01-16 05:52 UTC
