### ISSUE TITLE
gulp-watch don't action in new version?!

### ISSUE THREAD

**Issue by sajadabedi** [floatdrop/gulp-watch#188] opened 2015-07-22 08:38 UTC
Hi.
in new version of gulp-watch can't watch file. but gulp.watch do.

```
gulp.task('default', ['sass'], function () {
    browserSync.init({
      injectChanges: true,
      notify: false,
      server: {
        baseDir: "./app"
      }
    });
    watch('src/scss/**/*.scss', function() {
        gulp.start('sass');
    });
});
```

When i change scss file gulp-watch don't working.
how to fix that?

**Comment by floatdrop** [comment] 2015-07-22 09:19
Nope, working fine.

```
❯ node index.js
<File "root.scss" <Buffer 61 73 64 0a>>
<File "sub/deep.scss" <Buffer >>
<File "sub/deep.scss" <Buffer 61 73 64 73 61 0a>>

~/github.com/test-watch 13s
❯ cat index.js
var watch = require('gulp-watch');

watch('src/scss/**/*.scss', function(file) {
    console.log(file);
});
```

**Comment by sajadabedi** [comment] 2015-07-22 16:16
Thank you for relpy @floatdrop 
But I 'm still having issue!
Here my gulp file. please help me to fix this problem.

`````
var gulp        = require('gulp');
$               = require('gulp-load-plugins')();
var browserSync = require('browser-sync').create();
var reload      = browserSync.reload;
var watch       = require('gulp-watch');
var minifyCSS   = require('gulp-minify-css');

/*-------------------------------------------------------------------
    Configuration
-------------------------------------------------------------------*/
path = {
    app        : "app",
    css        : "app/assets/css",
    javascript : "app/assets/js",
    img        : "app/assets/img",
    fonts      : "app/assets/fonts",
    js         : "src/js",
    scss       : "src/scss",
    svg        : "src/svg",
    template   : "src/template"
}

var onError = $.notify.onError({
    message:  '<%= error.message %> :('
});

// Libsass + sourcemap
gulp.task('sass', function(){
    return gulp.src(path.scss + '/master.scss')
        .pipe($.plumber({errorHandler: onError}))
        .pipe($.sourcemaps.init())
        .pipe($.sass())
        .pipe($.sourcemaps.write('maps'))
        .pipe(gulp.dest(path.css))
        .pipe(reload({stream: true}));
});

gulp.task('cssmin', function(){
    return gulp.src(path.css + '/master.css')
        .pipe(minifyCSS())
        .pipe($.rename({suffix: '.min'}))
        .pipe(gulp.dest(path.css))
        .pipe(reload({stream: true}));
});

/**
 * Compile jade files into HTML
 */
var mixinPath = "!src/template/mixin/**";
var partialsPath = "!src/template/partials/**";
gulp.task('templates', function() {

    var YOUR_LOCALS = {};

    return gulp.src([path.template+ '/**/*.jade', mixinPath, partialsPath])
        .pipe($.plumber({errorHandler: onError}))
        .pipe($.jade({
            pretty: true,
            locals: YOUR_LOCALS
        }))
        .pipe(gulp.dest(path.app))
        .pipe(reload({stream: true}));
});

/**
 * Important!!
 * Separate task for the reaction to `.jade` files
 */
gulp.task('jade-watch', ['templates'], reload);


// javascript contact
gulp.task('scripts', function(){
    return gulp.src(path.js + '/libs/*.js')
        .pipe($.plumber({errorHandler: onError}))
        .pipe($.concat('plugins.js'))
        .pipe($.uglify())
        .pipe(gulp.dest(path.javascript))
        .pipe(reload({stream: true}));
});

// javascript minify
gulp.task('uglify', function(){
    return gulp.src(path.js + '/*.js')
        .pipe($.plumber({errorHandler: onError}))
        .pipe($.uglify())
        .pipe($.rename({suffix: '.min'}))
        .pipe(gulp.dest(path.javascript))
        .pipe(reload({stream: true}));
});

// Copy script file
gulp.task('copy', function(){
    return gulp.src(path.js + '/scripts.js')
        .pipe(gulp.dest(path.javascript));
});

// reload manual
gulp.task('bs-reload', function () {
    browserSync.reload();
});

/**
 * Serve and watch the scss/jade files for changes
 */
gulp.task('default', ['templates','sass'], function () {

    browserSync.init({
      injectChanges: true,
      notify: false,
      server: {
        baseDir: "./app"
      }
    });
    watch('src/scss/**/*.scss', function() { gulp.start('sass'); });
    watch('./src/template/**/*.jade', function() { gulp.start('jade-watch'); });
    watch('./app/img/**/*.*', function() { gulp.start('bs-reload'); });
    watch('./src/js/**/*.js', function() { gulp.start(['scripts','uglify','copy']); });
    //gulp.watch('./src/template/**/*.jade', ['jade-watch']);
    //gulp.watch('./app/img/**/*.*', ['bs-reload']);
    //gulp.watch('./src/js/**/*.js', ['scripts','uglify','copy']);
});

`````

**Comment by andrewzamojc** [comment] 2015-07-24 16:36
I created a simple example of the problem. It's a lot like yours floatdrop except mine doesn't print the output. The project only has three files: package.json, index.js, and watchme.js. The node_modules folder contains gulp-watch and its dependencies.

```
>cat package.json
{
  "devDependencies": {
    "gulp-watch": "4.3.3"
  }
}

>cat index.js
var watch = require('gulp-watch');
console.log('starting watch');
watch('./watchme.js', function(file) {
    console.log(file);
});

>cat watchme.js
some content

>npm install
>node index.js
starting watch
```

With that running, editing watchme.js in an editor, or touching it in a terminal does not trigger the watch (no output after 'starting watch'). None of the 4.3.x versions trigger the watch, I can't npm install 4.2.6 for some reason but 4.2.5 works well:

```
>cat package.json
{
  "devDependencies": {
    "gulp-watch": "4.2.5"
  }
}

>npm install
```
run index.js then in another terminal or text editor, touch the file

```
>node index.js
starting watch
<File "watchme.js" <Buffer 73 6f 6d 65 20 63 6f 6e 74 65 6e 74 32>>
```

I'm on OSX 10.10.3, node 0.12.7.

**Comment by hash-bang** [comment] 2015-08-14 00:48
I can confirm this behaviour on Linux.

Downgrading via `npm install gulp-watch@4.2.5` fixes the issue as per the advice of @andrewzamojc

**Comment by vithar** [comment] 2015-09-19 06:20
I can confirm. gulp-watch works for me in version 4.2.6 and doesn't in version >=4.3.0

**Comment by floatdrop** [comment] 2015-09-19 09:48
@vithar I have a little time for this module, could you provide a failing test? This would be helpful.

**Comment by floatdrop** [comment] 2015-09-20 12:19
`index.js` from @andrewzamojc 

![2015-09-20 17_17_56](https://cloud.githubusercontent.com/assets/365089/9980696/97fcf596-5fbb-11e5-93ba-dd4e7bb2171f.gif)

**Comment by vithar** [comment] 2015-09-20 18:16
У меня node 0.10, может в этом дело. Обновлю до 4.x, проверю и напишу.

**Comment by vithar** [comment] 2015-09-21 07:32
Перезагрузился и всё заработало.

**Comment by sjelfull** [comment] 2015-09-28 12:36
I'm seeing the same thing. Basically the same configuration. Got gulp-watch 4.3.5, node 0.12.2.

**Comment by natew** [comment] 2015-10-09 21:57
Does adding a ton of functions after your last one work? I did this:

```js
function pipefn(fn) {
  return through.obj(function(file, enc, next) {
    fn && fn(file)
    next(null, file);
  })
}

// gulp pipeline
.pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn())
    .pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn())
    .pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn())
    .pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn()).pipe(pipefn())
```

For some reason this fixes it, and the more I put after the less often it "doesn't run the pipeline".

**Comment by fabriceci** [comment] 2015-10-12 15:22
I have the same problem. I must use the older version (4.2.5) for detecting changes. I tried "gulp-starter" (clean config) and to add "usePolling=true" but the problem remains. I use MacOs X 10.11, perhaps it's this related.

**Comment by salex772** [comment] 2016-03-28 15:35
I have the same issue. gulp-watch 4.3.5 does not detect new files in path on OS X. But it tracks files changes. 

    gulp.watch(path.join(tasks.images.src, '*.{' + tasks.images.extensions.join(',') + '}'), ['images']);

**Comment by UltCombo** [comment] 2016-06-19 05:37
Please try out the latest version, I believe this should be fixed by now.

Also, remember, if you are watching files in a non-standard situation (e.g. network drive, shared folder with VM) you will likely need to enable the `usePolling` option.

**Closed by UltCombo** 2016-06-19 05:37 UTC

**Comment by rhiadj** [comment] 2016-07-10 03:35
In case this helps anyone in this thread - I was having similar problems - renamed a directory and everything magically started working! See:
https://github.com/floatdrop/gulp-watch/issues/244
