### ISSUE TITLE
Slowness with v4 vs. v3

### ISSUE THREAD

**Issue by mattfordham** [floatdrop/gulp-watch#132] opened 2015-02-04 00:45 UTC
Hi there. I am using this plugin alongside gulp-livereload like so:

```
gulp.task "watch", ->
  plugins.livereload.listen()

  plugins.watch "#{config.sourcePath}/#{config.cssDirectory}/**/*.styl", ->
    gulp.start "stylesheets"

  plugins.watch "#{config.publicPath}/**/*"
    .pipe plugins.livereload()

  return
```
With version 3.0.0, CSS updates were instant. With v4.1.0, however, a few seconds go by before the browser refreshes... and it is somewhat inconsistent (sometimes 1 second, sometimes up to 10). 

Any ideas what's up?

**Comment by floatdrop** [comment] 2015-02-08 13:42
@mattfordham we switched from `gaze` to `chokidar`. It can be, that you are using polling instead of superfast `fsevents`. What is your version of node/OS?

**Comment by mattfordham** [comment] 2015-02-08 21:09
I'm using Gulp Watch 4.1.1, Node 0.12.0, and OSX 10.10.1. I previous was having the issue with Node 0.10... updating to latest didn't help. 

How can I confirm if fsevents is working (or not)?

**Comment by floatdrop** [comment] 2015-02-14 17:25
Only hint I know of - is that you get this output (when run `npm install`):

```
> fsevents@0.3.5 install /Users/floatdrop/watch-events-problem/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
```

**Comment by mattfordham** [comment] 2015-02-14 17:40
Hmm... yeah I get that ouput... no errors. It seems like everything is installed as expected. But still, very slow :(   I'll keep poking around.

**Comment by igidas** [comment] 2015-02-19 12:50
I get same error with "gulp-sass" after switching to new version of "gulp-watch".
Looks like, that compile time increases after each compile, when watching files.
First compile tooks 53ms, after just adding space character in one of scss files, compile time starts to increase: 77ms, 84ms, 93ms, 105ms and continues...

**Comment by mattfordham** [comment] 2015-02-19 16:39
@igidas that describes my issue pretty closely. Glad I'm not crazy :)

**Comment by romaintb** [comment] 2015-02-24 14:00
Hi guys,
Linux here, node 0.10.36, gulp-watch 4.1.1, and I see the same issues. Overnight I even get an out of memory error : 
```
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
[1]    25161 abort      gulp watch
```
The time from blazing fast to unusably slow is really quick.

**Comment by stevenjlho** [comment] 2015-02-27 05:17
I have the same issue. Node 0.12.0, and OS X 10.10.2.

**Comment by floatdrop** [comment] 2015-03-01 07:31
> Any ideas what's up?

I think we got vinyl objects stuck in stream buffer when callback is used. Could you attach `.on('data', function(){})` to `plugins.watch` calls and test that it still the issue?

**Comment by floatdrop** [comment] 2015-03-01 15:17
Pushed possible fix to master, could someone verify, that it fix issue?

```
npm install https://github.com/floatdrop/gulp-watch/tarball/master
```

**Comment by mattfordham** [comment] 2015-03-01 21:37
I'm afraid things are still slow for me. I did the ".on(data..." thing too... still no luck. 

One note of possible relevance... within ".on(data..." I put a log, to make sure it was working. The log happens immediately, but the live-reloading is still delayed. I would blame it on live-reload, but again, if I switch back to v3, all is well again.

**Comment by romaintb** [comment] 2015-03-03 11:13
same here, no trace of improvement unfortunately

**Comment by gustavohenke** [comment] 2015-03-12 13:04
So, after my issue #133 has been closed, I've been trying version 4 of gulp-watch.
Looks like I'm also another victim of this slowness, all files are inconsistently taking ~10s to be processed. Sometimes even 25s.

Another issue I observed is that the tasks used ~250 MB of memory with v3, now they're using _from start_ ~380 MB, and as watchers are triggered, the memory usage goes up to 500 MB.

I'll try with the latest commits to master and report my results.

**Comment by gustavohenke** [comment] 2015-03-12 13:13
No results...

```
[10:11:42] evento\acoes-evento.controller.js was changed
[10:11:42] Starting 'js'...
[10:11:44] Finished 'js' after 1.48 s
[10:11:49] evento\acoes-evento.controller.js was changed
[10:11:49] Starting 'js'...
[10:11:52] Finished 'js' after 3.35 s
[10:11:59] evento\acoes-evento.controller.js was changed
[10:11:59] Starting 'js'...
[10:12:03] Finished 'js' after 4 s
[10:12:07] evento\acoes-evento.controller.js was changed
[10:12:07] Starting 'js'...
[10:12:13] Finished 'js' after 6.03 s
[10:12:18] evento\acoes-evento.controller.js was changed
[10:12:18] Starting 'js'...
[10:12:21] evento\acoes-evento.controller.js was changed
[10:12:28] Finished 'js' after 9.87 s
[10:12:38] evento\acoes-evento.controller.js was changed
[10:12:38] Starting 'js'...
[10:12:51] Finished 'js' after 13 s
```

**Comment by noahgrant** [comment] 2015-03-15 21:13
@floatdrop this is a separate issue, but since you referenced it here, I am using the callback pattern, and the vinyl File object becomes a Buffer at some point.  Tried installing from master, but it still breaks on any task every time.  Should we open a separate issue for this?

**Comment by floatdrop** [comment] 2015-03-16 04:58
@noahgrant please open new issue for this. It would be greate, if you also check, what `gulp-watch` emits with `.on('data', function(file){console.log(file);})`

**Comment by floatdrop** [comment] 2015-03-16 16:55
@gustavohenke seems like watch event is launched, but `js` task takes longer and longer. Could you post your gulpfile?

**Comment by igidas** [comment] 2015-03-26 23:40
Any updates?

**Comment by gustavohenke** [comment] 2016-05-02 02:37
So, it's been more than a year since the last update in this thread.
I'm now working on another project, with another Node version; the problems are way smaller, but still noticeable when compared to the gulp's built-in `gulp.watch` function.

The execution times are growing in a slower pace than what it used to be, it takes like 10 saves of 1 byte to increase 5x the initial execution time; however, this is still annoying.

Here's a gist that replicates my issues on Windows 10:
https://gist.github.com/gustavohenke/3381d0e2de51f0c95438ba499f5a2c04

**Comment by strohhut** [comment] 2016-06-17 21:33
After gulp-watch executes the callback a couple of times it gets incredibly slow. I tried different tasks as callbacks and also executed the callback tasks repeatedly without gulp-watch. The problem only happens when gulp-watch is used.

**Comment by UltCombo** [comment] 2016-06-19 05:29
Hey people.

It looks like the initial issue reported here has been fixed.

The last two comments mention gulp-watch getting slower as events are triggered, so I'm assuming that is due to bad usage. Please make sure your code does not call `watch()` inside a callback (or task) that gets executed multiple times, otherwise you will be constantly adding new file system watchers every time your callback/task runs. In fact, I've noticed one of the README's examples contained this blatant flaw and I have now fixed it. Please review the [usage examples](https://github.com/floatdrop/gulp-watch#usage) if you need help.

If you are unable to find the flaw or to adapt your code accordingly, please post your gulpfile and I'll take a look.

**Closed by UltCombo** 2016-06-19 05:29 UTC

**Comment by gustavohenke** [comment] 2016-06-19 21:37
> please post your gulpfile

That's exactly what I did previously, still got not response.

**Comment by UltCombo** [comment] 2016-06-19 21:43
You mean the [gist above](https://gist.github.com/gustavohenke/3381d0e2de51f0c95438ba499f5a2c04)? My bad, I've skipped the link.

Your gulpfile looks fine, with the exception that `server.stream()` is alien there—`server` is not defined. Let me know if you can fix the sample and still reproduce the issue, I'll try it then.

**Comment by strohhut** [comment] 2016-06-20 18:16
@UltCombo One of my tasks simply compilesTypeScript files, another one Sass files. There are no recursive tasks calls. Like I said calling the same task with `gulp.watch` maintains the same speed unlike gulp-watch so I don't think my tasks are the issue.

**Comment by UltCombo** [comment] 2016-06-20 18:46
I'm using gulp-watch on several projects, in both Windows 10 and OS X 10.11, and I haven't experienced any noticeable perf issues so far.

This plugin basically wraps a file system watcher ([Chokidar](https://github.com/paulmillr/chokidar)) and emit vinyl files. The major difference between v3 and v4 is that we have switched the underlying file system from Gaze to Chokidar, so what you may be experiencing is some specific issue with Chokidar.

Are you on Windows? If so, please subscribe to this [Chokidar issue](https://github.com/paulmillr/chokidar/issues/328) and post any findings there. The information will be far more useful at the root of the problem, where they can actually do something about the issue and fix it.

**Comment by gustavohenke** [comment] 2016-06-21 02:32
Hi @UltCombo, I updated the gist with missing variable!

**Comment by strohhut** [comment] 2016-06-21 12:17
@UltCombo Yes I'm on windows, I'll look at the issue thanks!

**Comment by UltCombo** [comment] 2016-06-24 02:31
@gustavohenke Can you try setting the `{ usePolling: true }` option to see if it helps?
